name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      working-directory: ./

    - name: Run tests
      run: npm test
      working-directory: ./

    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v2
      with:
        app-name: healthcare-backend
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./
